name: Workflow Manager

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  download-content:
    name: ğŸ“¦ Workflow Manager
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ—‘ï¸ Cleanup Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_run_by_conclusion_pattern: cancelled,skipped,failure,action_required
          keep_minimum_runs: 0
          retain_days: 0
